language: python
python:
- 3.6
before_install:
- pip install poetry
install:
- poetry install
script:
- pre-commit run --all-files
- poetry run pytest --cov=mob_assistant
after_success:
- codecov
env:
  global:
  - secure: G4sM7Qryd6y4R17WE+C2BWUp3btodCdQ6ceAT9XYmVlAHwTe8FMf+7mVmbwq4yN0me078mJYDOoAZLNoW4yFIxKH55V0m22Omgl8JQorJdiG1A60D9161nhVYeZHnuC4JMm2A/kwbeQe07D39D+LqDqtv4rK4BQnlrs61nzjx7BFRMPSEm4YECkeMRPq5fM/u9Mi+bWH6vRIe5CjNGvpp9dbeY4JYUXNq5LcY6fA18YwgDyDRHLr2jCz/zc/YRvUSPkIzM1ApL85Co3FyQKCxkFENwiNTyUP00c/yqq8HWaceBQhcy9KniR/xpygz+WMBTKbagKQFZwcFxj7XB2n5y46JPwKmPya/zwfyR7C3vgnFrNg9QF+IHxrqEobm3/KD7iD64D527wGxTGINmUkUfbzXGOAEcjUJE9US4lFR47wx03x7FLMn5NsEp2YOznO4jdHTtrtrq+XrWRoEB6HOizDGIif7Ds3LMbhpznzV/knCLMDHxGL5ANxQue3PL0VCUH8FtYoIWdQCQsuEw/NrdRoK9a9OF8C29U5t3JNsCvknHrYObD5an5cjKzuxXhyf73O5xeep2QI4phJimV0K0JaAuspS2ipTXHqudYCv1kPiH1okXc4WbmLqKevAYzzgR1i+jIinoCZDw7rJMTPaNmeBINukhPPMWEQsLfXXH0=
  - secure: bJDK1AgeR9aLfGPt8PDUqIFlbTd3dL5KgjK29lUIEknfhgwE/FhBksEB5ZH8QqxmvbfmRlIOYcfABF5yH6fSicOcyNdApRwdkHivF1njbWXXJBZucNwq6nCtjTRjnX50Yby05xAwYZYB8T/d2CIn6mM0QlpDx5bFVwuHRQ0Hgy79HFyOlOuZBgp1FsdFy80QxyB70bN8PhBYrNwuwF8vWB0iOaEe2swAYg+1JNJ0NQk6UYV9QbSui1kpeGMy4CBIyC02yp3Uq0m3UVVSWBhcWy+IMiGaOodfL0yM/BaW7JWKJtHldJujzC6OB7Uj3zZWk/WGD98snHgimorfwsLcIvFue0XTyB+HbYFMkoveQNK26nU3gjAIusHAD5pCBRKjDgjtVUrkTJXUDZQ0rw0KS/4ei+C8bbKOxnr9zTNUtZAmSMdh5vHvoMTnw2DTn2muBwWWXCtq+omam3WmQfjy4Lrw3T47gS2EwKXZ+cGKF7q65NOUG0YTfcOYfFv32/BdM7y+wfybDPDnVkLZ5guZ3NAgyoA2eRm71vcFVLBfXdWBuCJpVmhS6KwO0jCUUFP1joX6nprY92Wj0k7I1nSEUy+WJzrO6I2mXwn3N8vqUPt3a5o602OpZfZYinSWY1Su23oUu9M8aAcACNacL4FTB4t0s9z5qedpoVjT6QW/V8o=
before_deploy:
- poetry build
deploy:
  provider: script
  script: poetry publish --username $PYPI_USER --password $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
